import { jsPDF } from "jspdf";
import "./ReportViewer.css";
import ReactMarkdown from "react-markdown";

function ReportViewer({
  report,
  industry,
  country,
  reportType,
}) {

  const copyReport = () => {
  navigator.clipboard.writeText(report);

  alert("✅ Report copied successfully!");
};

const downloadPDF = () => {
  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
doc.setFontSize(22);
doc.text("AI Market Research Report", 20, 20);

doc.setFont("helvetica", "normal");
doc.setFontSize(12);

doc.text(`Industry: ${industry}`, 20, 35);
doc.text(`Country: ${country}`, 20, 43);
doc.text(`Report Type: ${reportType}`, 20, 51);
doc.text("Generated By: Gemini AI", 20, 59);
doc.text(
  `Generated On: ${new Date().toLocaleDateString()}`,
  20,
  67
);

// Divider
doc.line(20, 75, 190, 75);

  const cleanReport = report
  .replace(/^###\s/gm, "")
  .replace(/^##\s/gm, "")
  .replace(/^#\s/gm, "")
  .replace(/\*\*/g, "")
  .replace(/^\*\s/gm, "• ")
  .replace(/^---$/gm, "");

const lines = doc.splitTextToSize(cleanReport, 170);

let y = 85;

lines.forEach((line) => {

  if (y > 280) {
    doc.addPage();
    y = 20;
  }

  doc.text(line, 20, y);
  y += 7;

});

  doc.save("Market_Research_Report.pdf");
};


  console.log("Report Received:", report);

  return (
    <div className="report-container">
      <h2>📄 AI Market Research Report</h2>

      <div className="report-info">
  <div>
    <strong>Industry:</strong> {industry}
  </div>

  <div>
    <strong>Country:</strong> {country}
  </div>

  <div>
    <strong>Report Type:</strong> {reportType}
  </div>

  <div>
    <strong>Generated By:</strong> Gemini AI
  </div>

  <div>
    <strong>Generated On:</strong> {new Date().toLocaleDateString()}
  </div>
</div>
<div className="report-actions">
  <button
    className="copy-btn"
    onClick={copyReport}
  >
    📋 Copy Report
  </button>

  <button
  className="pdf-btn"
  onClick={downloadPDF}
>
  📄 Download PDF
</button>

</div>
      <ReactMarkdown>{report}</ReactMarkdown>
    </div>
  );
}

export default ReportViewer;