import "./ReportViewer.css";
import ReactMarkdown from "react-markdown";

function ReportViewer({
  report,
  industry,
  country,
  reportType,
}) {

  const copyReport = () => {
  navigator.clipboard.writeText(report);

  alert("✅ Report copied successfully!");
};
  console.log("Report Received:", report);

  return (
    <div className="report-container">
      <h2>📄 AI Market Research Report</h2>

      <div className="report-info">
  <div>
    <strong>Industry:</strong> {industry}
  </div>

  <div>
    <strong>Country:</strong> {country}
  </div>

  <div>
    <strong>Report Type:</strong> {reportType}
  </div>

  <div>
    <strong>Generated By:</strong> Gemini AI
  </div>

  <div>
    <strong>Generated On:</strong> {new Date().toLocaleDateString()}
  </div>
</div>
<div className="report-actions">
  <button
    className="copy-btn"
    onClick={copyReport}
  >
    📋 Copy Report
  </button>
</div>
      <ReactMarkdown>{report}</ReactMarkdown>
    </div>
  );
}

export default ReportViewer;